/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c dualshock4_workerInterface -a dualshock4_worker_interface.h:dualshock4_worker_interface.cpp com.robot.dualshock4_worker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DUALSHOCK4_WORKER_INTERFACE_H
#define DUALSHOCK4_WORKER_INTERFACE_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.robot.rogamepad.dualshock4
 */
class dualshock4_workerInterface: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.robot.rogamepad.dualshock4")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.robot.rogamepad.dualshock4\">\n"
"    <signal name=\"error\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"bError\"/>\n"
"    </signal>\n"
"    <signal name=\"connected\"/>\n"
"    <signal name=\"disconnected\"/>\n"
"    <signal name=\"buttonPS\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"axisLeftX\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </signal>\n"
"    <signal name=\"axisLeftY\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </signal>\n"
"    <signal name=\"axisRightX\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </signal>\n"
"    <signal name=\"axisRightY\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonL1\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonR1\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonL2\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonR2\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonOpt\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonShare\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonA\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonB\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonY\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"buttonX\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"capacityChanged\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </signal>\n"
"    <signal name=\"statusChanged\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </signal>\n"
"    <method name=\"getName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getAddress\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getPluginType\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getDescription\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"isEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"isConnected\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"bEnabled\"/>\n"
"    </method>\n"
"    <method name=\"redLedValue\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"greenLedValue\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"blueLedValue\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"getCapacity\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getStatus\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    dualshock4_workerInterface(QObject *parent);
    virtual ~dualshock4_workerInterface();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void blueLedValue(int value);
    QString getAddress();
    int getCapacity();
    QString getDescription();
    QString getName();
    QString getPluginType();
    QString getStatus();
    void greenLedValue(int value);
    bool isConnected();
    bool isEnabled();
    void redLedValue(int value);
    void setEnabled(bool bEnabled);
Q_SIGNALS: // SIGNALS
    void axisLeftX(double in0);
    void axisLeftY(double in0);
    void axisRightX(double in0);
    void axisRightY(double in0);
    void buttonA(bool in0);
    void buttonB(bool in0);
    void buttonL1(bool in0);
    void buttonL2(bool in0);
    void buttonOpt(bool in0);
    void buttonPS(bool in0);
    void buttonR1(bool in0);
    void buttonR2(bool in0);
    void buttonShare(bool in0);
    void buttonX(bool in0);
    void buttonY(bool in0);
    void capacityChanged(int in0);
    void connected();
    void disconnected();
    void error(bool bError);
    void statusChanged(const QString &in0);
};

#endif
