/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c balltracker_workerInterface com.robot.balltracker_worker.xml -p balltracker_worker_proxy.h:balltracker_worker_proxy.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "balltracker_worker_proxy.h"

/*
 * Implementation of interface class balltracker_workerInterface
 */

balltracker_workerInterface::balltracker_workerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

balltracker_workerInterface::~balltracker_workerInterface()
{
}

