/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c roenginesInterface -a roengines_interface.h:roengines_interface.cpp com.robot.roengines.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "roengines_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class roenginesInterface
 */

roenginesInterface::roenginesInterface(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

roenginesInterface::~roenginesInterface()
{
    // destructor
}

QStringList roenginesInterface::getObjects()
{
    // handle method call com.robot.roengines.getObjects
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjects", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QStringList roenginesInterface::getObjectsByName(const QString &strName)
{
    // handle method call com.robot.roengines.getObjectsByName
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByName", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strName));
    return out0;
}

QStringList roenginesInterface::getObjectsByType(const QString &strType)
{
    // handle method call com.robot.roengines.getObjectsByType
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByType", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strType));
    return out0;
}

QString roenginesInterface::getVersion()
{
    // handle method call com.robot.roengines.getVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "getVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

