/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c stream_workerInterface -a stream_worker_interface.h:stream_worker_interface.cpp com.robot.stream_worker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STREAM_WORKER_INTERFACE_H
#define STREAM_WORKER_INTERFACE_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.zitro.zone.zoaudio
 */
class stream_workerInterface: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.zitro.zone.zoaudio")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.zitro.zone.zoaudio\">\n"
"    <signal name=\"error\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"bError\"/>\n"
"    </signal>\n"
"    <method name=\"getName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getAddress\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getPluginType\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getDescription\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"isEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setEnabled\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"bEnabled\"/>\n"
"    </method>\n"
"    <method name=\"start\"/>\n"
"  </interface>\n"
        "")
public:
    stream_workerInterface(QObject *parent);
    virtual ~stream_workerInterface();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString getAddress();
    QString getDescription();
    QString getName();
    QString getPluginType();
    bool isEnabled();
    void setEnabled(bool bEnabled);
    void start();
Q_SIGNALS: // SIGNALS
    void error(bool bError);
};

#endif
