/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c stream_workerInterface -a stream_worker_interface.h:stream_worker_interface.cpp com.robot.stream_worker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "stream_worker_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class stream_workerInterface
 */

stream_workerInterface::stream_workerInterface(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

stream_workerInterface::~stream_workerInterface()
{
    // destructor
}

QString stream_workerInterface::getAddress()
{
    // handle method call com.zitro.zone.zoaudio.getAddress
    QString out0;
    QMetaObject::invokeMethod(parent(), "getAddress", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString stream_workerInterface::getDescription()
{
    // handle method call com.zitro.zone.zoaudio.getDescription
    QString out0;
    QMetaObject::invokeMethod(parent(), "getDescription", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString stream_workerInterface::getName()
{
    // handle method call com.zitro.zone.zoaudio.getName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString stream_workerInterface::getPluginType()
{
    // handle method call com.zitro.zone.zoaudio.getPluginType
    QString out0;
    QMetaObject::invokeMethod(parent(), "getPluginType", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool stream_workerInterface::isEnabled()
{
    // handle method call com.zitro.zone.zoaudio.isEnabled
    bool out0;
    QMetaObject::invokeMethod(parent(), "isEnabled", Q_RETURN_ARG(bool, out0));
    return out0;
}

void stream_workerInterface::setEnabled(bool bEnabled)
{
    // handle method call com.zitro.zone.zoaudio.setEnabled
    QMetaObject::invokeMethod(parent(), "setEnabled", Q_ARG(bool, bEnabled));
}

void stream_workerInterface::start()
{
    // handle method call com.zitro.zone.zoaudio.start
    QMetaObject::invokeMethod(parent(), "start");
}

