/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c balltracker_workerInterface -a balltracker_worker_interface.h:balltracker_worker_interface.cpp com.robot.balltracker_worker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "balltracker_worker_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class balltracker_workerInterface
 */

balltracker_workerInterface::balltracker_workerInterface(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

balltracker_workerInterface::~balltracker_workerInterface()
{
    // destructor
}

QString balltracker_workerInterface::getAddress()
{
    // handle method call com.robot.tracker.getAddress
    QString out0;
    QMetaObject::invokeMethod(parent(), "getAddress", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString balltracker_workerInterface::getDescription()
{
    // handle method call com.robot.tracker.getDescription
    QString out0;
    QMetaObject::invokeMethod(parent(), "getDescription", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString balltracker_workerInterface::getName()
{
    // handle method call com.robot.tracker.getName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString balltracker_workerInterface::getPluginType()
{
    // handle method call com.robot.tracker.getPluginType
    QString out0;
    QMetaObject::invokeMethod(parent(), "getPluginType", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool balltracker_workerInterface::isEnabled()
{
    // handle method call com.robot.tracker.isEnabled
    bool out0;
    QMetaObject::invokeMethod(parent(), "isEnabled", Q_RETURN_ARG(bool, out0));
    return out0;
}

void balltracker_workerInterface::setEnabled(bool bEnabled)
{
    // handle method call com.robot.tracker.setEnabled
    QMetaObject::invokeMethod(parent(), "setEnabled", Q_ARG(bool, bEnabled));
}

void balltracker_workerInterface::startStreaming()
{
    // handle method call com.robot.tracker.startStreaming
    QMetaObject::invokeMethod(parent(), "startStreaming");
}

void balltracker_workerInterface::startStreamingSock()
{
    // handle method call com.robot.tracker.startStreamingSock
    QMetaObject::invokeMethod(parent(), "startStreamingSock");
}

