/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c gamepad_managerInterface -a gamepad_manager_interface.h:gamepad_manager_interface.cpp com.robot.gamepad_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "gamepad_manager_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class gamepad_managerInterface
 */

gamepad_managerInterface::gamepad_managerInterface(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

gamepad_managerInterface::~gamepad_managerInterface()
{
    // destructor
}

QStringList gamepad_managerInterface::getObjects()
{
    // handle method call com.robot.rogamepad.getObjects
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjects", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QStringList gamepad_managerInterface::getObjectsByName(const QString &strName)
{
    // handle method call com.robot.rogamepad.getObjectsByName
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByName", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strName));
    return out0;
}

QStringList gamepad_managerInterface::getObjectsByType(const QString &strType)
{
    // handle method call com.robot.rogamepad.getObjectsByType
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByType", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strType));
    return out0;
}

QString gamepad_managerInterface::getVersion()
{
    // handle method call com.robot.rogamepad.getVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "getVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

