/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c rotracking_managerInterface -a rotracking_manager_interface.h:rotracking_manager_interface.cpp com.robot.rotracking_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "rotracking_manager_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class rotracking_managerInterface
 */

rotracking_managerInterface::rotracking_managerInterface(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

rotracking_managerInterface::~rotracking_managerInterface()
{
    // destructor
}

QStringList rotracking_managerInterface::getObjects()
{
    // handle method call com.robot.rotracking.getObjects
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjects", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QStringList rotracking_managerInterface::getObjectsByName(const QString &strName)
{
    // handle method call com.robot.rotracking.getObjectsByName
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByName", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strName));
    return out0;
}

QStringList rotracking_managerInterface::getObjectsByType(const QString &strType)
{
    // handle method call com.robot.rotracking.getObjectsByType
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectsByType", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, strType));
    return out0;
}

QString rotracking_managerInterface::getVersion()
{
    // handle method call com.robot.rotracking.getVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "getVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

