/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c rotracking_managerInterface com.robot.rotracking_manager.xml -p rotracking_manager_proxy.h:rotracking_manager_proxy.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "rotracking_manager_proxy.h"

/*
 * Implementation of interface class rotracking_managerInterface
 */

rotracking_managerInterface::rotracking_managerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

rotracking_managerInterface::~rotracking_managerInterface()
{
}

